In [145]:
import pandas as pd
import numpy as np

In [146]:
df = pd.read_csv("MLF_GP1_CreditScore.csv")
df

,Sales/Revenues,Gross Margin,EBITDA,EBITDA Margin,Net Income Before Extras,Total Debt,Net Debt,LT Debt,ST Debt,Cash,...,Interest Coverage,Total Liquidity,Current Liquidity,Current Liabilities,EPS Before Extras,PE,ROA,ROE,InvGrd,Rating
0,-0.005496,0.030763,0.018885,0.024515,0.146849,-0.029710,-0.019296,-0.042648,0.049875,-0.133716,...,0.136748,0.392143,-0.184887,0.062781,0.148305,0.100409,0.163266,0.102521,1,A1
1,-0.005496,0.030763,0.088716,0.094733,0.146849,-0.029710,-0.019296,-0.042648,0.049875,-0.133716,...,0.214657,0.392143,-0.184887,0.062781,0.148305,-0.089598,0.163266,0.102521,1,A1
2,-0.007045,0.023159,0.088716,0.096440,0.108590,0.039410,0.034268,0.009059,0.250371,0.101315,...,0.205290,0.483257,-0.017877,0.121357,0.110656,-0.045142,0.105711,0.103378,1,A1
3,-0.009396,0.028400,0.088716,0.099046,0.146137,0.030071,0.036938,-0.016964,0.356994,-0.052606,...,0.232991,0.996955,-0.122017,0.079051,0.151639,-0.008231,0.162421,0.132295,1,A1
4,-0.009009,0.027714,0.088716,0.098611,0.123500,0.024224,0.034445,-0.034132,0.461894,-0.090869,...,0.172906,1.711426,-0.161561,0.084319,0.130435,0.015528,0.156427,0.225144,1,A1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1695,-0.099327,-0.010702,-0.127046,-0.030785,-4.349569,0.124830,0.146400,0.008407,0.364676,-0.028333,...,-0.190974,0.603271,-0.150779,0.144187,-4.408257,-1.339781,-4.271318,-5.168673,0,Caa1
1696,-0.116919,-0.009799,-0.155183,-0.043333,-2.937747,0.157873,0.066243,0.084104,0.309846,0.808505,...,-0.246259,0.007110,0.604043,0.127468,-2.977064,-1.695900,-2.868086,-3.429429,0,Caa1
1697,-0.099676,0.067595,-0.170022,-0.078134,-1.960264,0.023226,-0.201398,0.024856,0.020078,1.352542,...,-0.266848,-0.959809,1.227363,0.056198,-1.955285,-1.919739,-1.876336,-1.940995,0,Caa1
1698,-0.088853,0.007820,-0.122645,-0.037088,-2.066509,0.067495,-0.011377,0.289219,-0.171802,0.671224,...,-0.226685,-0.438389,0.865331,-0.104059,-2.059347,-1.462429,-2.027254,-2.059961,0,Caa1
1699,-0.084739,-0.021961,-0.159290,-0.081442,-1.953166,-0.043481,-0.285966,0.045902,-0.179549,1.987960,...,-0.219651,-0.977050,2.167547,-0.056695,-1.948856,-1.918602,-1.952314,-1.758980,0,Caa1

Target column needs to be converted to numeric values

In [147]:
def rating_grouping(row):

  high = ["Aa1", "Aa2", "Aa3" , "Aaa"]
  upper_mid = ["A1", "A2", "A3"]
  lower_mid = ["Baa1", "Baa2", "Baa3"]
  spec = ["Ba1", "Ba2", "Ba3"]
  high_spec = ["B1", "B2", "B3"]
  Caa = ["Caa1", "Caa2", "Caa3"]
  Ca = ["Ca1", "Ca2", "Ca3"]
  C = ["C1", "C2", "C3"]



  
  if (row.Rating in high):
    return 1 #High Grade
  elif (row.Rating in upper_mid):
    return 2 #High Medium
  elif (row.Rating in lower_mid):
    return 3 #Lower Medium"
  elif (row.Rating in spec):
    return 4 #Speculative"
  elif (row.Rating in high_spec):
    return 5 #Highly Speculative"
  elif (row.Rating in Caa):
    return 6 #Substantial Risk"
  elif (row.Rating in Ca):
    return 7 #Near Default"
  elif (row.Rating in C):
    return 8 #In Default"

In [148]:
df["Rating_Group"] = df.apply(rating_grouping, axis=1)
df

,Sales/Revenues,Gross Margin,EBITDA,EBITDA Margin,Net Income Before Extras,Total Debt,Net Debt,LT Debt,ST Debt,Cash,...,Total Liquidity,Current Liquidity,Current Liabilities,EPS Before Extras,PE,ROA,ROE,InvGrd,Rating,Rating_Group
0,-0.005496,0.030763,0.018885,0.024515,0.146849,-0.029710,-0.019296,-0.042648,0.049875,-0.133716,...,0.392143,-0.184887,0.062781,0.148305,0.100409,0.163266,0.102521,1,A1,2
1,-0.005496,0.030763,0.088716,0.094733,0.146849,-0.029710,-0.019296,-0.042648,0.049875,-0.133716,...,0.392143,-0.184887,0.062781,0.148305,-0.089598,0.163266,0.102521,1,A1,2
2,-0.007045,0.023159,0.088716,0.096440,0.108590,0.039410,0.034268,0.009059,0.250371,0.101315,...,0.483257,-0.017877,0.121357,0.110656,-0.045142,0.105711,0.103378,1,A1,2
3,-0.009396,0.028400,0.088716,0.099046,0.146137,0.030071,0.036938,-0.016964,0.356994,-0.052606,...,0.996955,-0.122017,0.079051,0.151639,-0.008231,0.162421,0.132295,1,A1,2
4,-0.009009,0.027714,0.088716,0.098611,0.123500,0.024224,0.034445,-0.034132,0.461894,-0.090869,...,1.711426,-0.161561,0.084319,0.130435,0.015528,0.156427,0.225144,1,A1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1695,-0.099327,-0.010702,-0.127046,-0.030785,-4.349569,0.124830,0.146400,0.008407,0.364676,-0.028333,...,0.603271,-0.150779,0.144187,-4.408257,-1.339781,-4.271318,-5.168673,0,Caa1,6
1696,-0.116919,-0.009799,-0.155183,-0.043333,-2.937747,0.157873,0.066243,0.084104,0.309846,0.808505,...,0.007110,0.604043,0.127468,-2.977064,-1.695900,-2.868086,-3.429429,0,Caa1,6
1697,-0.099676,0.067595,-0.170022,-0.078134,-1.960264,0.023226,-0.201398,0.024856,0.020078,1.352542,...,-0.959809,1.227363,0.056198,-1.955285,-1.919739,-1.876336,-1.940995,0,Caa1,6
1698,-0.088853,0.007820,-0.122645,-0.037088,-2.066509,0.067495,-0.011377,0.289219,-0.171802,0.671224,...,-0.438389,0.865331,-0.104059,-2.059347,-1.462429,-2.027254,-2.059961,0,Caa1,6
1699,-0.084739,-0.021961,-0.159290,-0.081442,-1.953166,-0.043481,-0.285966,0.045902,-0.179549,1.987960,...,-0.977050,2.167547,-0.056695,-1.948856,-1.918602,-1.952314,-1.758980,0,Caa1,6

Separate target and feature datasets

In [149]:
X = df.drop(['InvGrd', 'Rating', 'Rating_Group'], axis=1)
X = X.drop(["Total Debt", "Total Debt/MV", "Net Debt", "Net Debt/MV", "Net Income Before Extras"], axis=1)
y = df['Rating_Group']
X

,Sales/Revenues,Gross Margin,EBITDA,EBITDA Margin,LT Debt,ST Debt,Cash,Free Cash Flow,Total Debt/EBITDA,Net Debt/EBITDA,...,CFO/Debt,CFO,Interest Coverage,Total Liquidity,Current Liquidity,Current Liabilities,EPS Before Extras,PE,ROA,ROE
0,-0.005496,0.030763,0.018885,0.024515,-0.042648,0.049875,-0.133716,0.352997,-0.047694,-0.037474,...,0.101245,0.068526,0.136748,0.392143,-0.184887,0.062781,0.148305,0.100409,0.163266,0.102521
1,-0.005496,0.030763,0.088716,0.094733,-0.042648,0.049875,-0.133716,0.352997,-0.108776,-0.099211,...,0.101245,0.068526,0.214657,0.392143,-0.184887,0.062781,0.148305,-0.089598,0.163266,0.102521
2,-0.007045,0.023159,0.088716,0.096440,0.009059,0.250371,0.101315,0.500174,-0.045288,-0.050011,...,0.027638,0.068136,0.205290,0.483257,-0.017877,0.121357,0.110656,-0.045142,0.105711,0.103378
3,-0.009396,0.028400,0.088716,0.099046,-0.016964,0.356994,-0.052606,0.551592,-0.053866,-0.047559,...,0.042437,0.073784,0.232991,0.996955,-0.122017,0.079051,0.151639,-0.008231,0.162421,0.132295
4,-0.009009,0.027714,0.088716,0.098611,-0.034132,0.461894,-0.090869,0.753321,-0.059237,-0.049849,...,0.106052,0.132845,0.172906,1.711426,-0.161561,0.084319,0.130435,0.015528,0.156427,0.225144
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1695,-0.099327,-0.010702,-0.127046,-0.030785,0.008407,0.364676,-0.028333,1.106048,0.288532,0.313242,...,0.348290,0.516587,-0.190974,0.603271,-0.150779,0.144187,-4.408257,-1.339781,-4.271318,-5.168673
1696,-0.116919,-0.009799,-0.155183,-0.043333,0.084104,0.309846,0.808505,3.336889,0.370560,0.262099,...,1.453531,1.840865,-0.246259,0.007110,0.604043,0.127468,-2.977064,-1.695900,-2.868086,-3.429429
1697,-0.099676,0.067595,-0.170022,-0.078134,0.024856,0.020078,1.352542,-2.531238,0.232835,-0.037804,...,-2.785428,-2.826901,-0.266848,-0.959809,1.227363,0.056198,-1.955285,-1.919739,-1.876336,-1.940995
1698,-0.088853,0.007820,-0.122645,-0.037088,0.289219,-0.171802,0.671224,-0.688930,0.216720,0.126822,...,-0.584309,-0.556247,-0.226685,-0.438389,0.865331,-0.104059,-2.059347,-1.462429,-2.027254,-2.059961
1699,-0.084739,-0.021961,-0.159290,-0.081442,0.045902,-0.179549,1.987960,2.148336,0.137752,-0.150677,...,1.915894,1.789100,-0.219651,-0.977050,2.167547,-0.056695,-1.948856,-1.918602,-1.952314,-1.758980


Split the data

In [272]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

In [151]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()

Initialize Pipeline

In [152]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42, class_weight="balanced_subsample")
rf_pipe = Pipeline([
    ("scaler", scaler),
    ("rf", rf)
])

In [153]:
from sklearn.model_selection import RepeatedStratifiedKFold
cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=2, random_state=42)

In [154]:
param_grid = {
    "rf__n_estimators":      [300, 600, 900, 1200],        
    "rf__max_depth":         [None, 8, 12, 16],      
    "rf__min_samples_split": [2, 5, 10],
    "rf__min_samples_leaf":  [1, 2, 4],
    "rf__max_features":      ["sqrt", "log2", 0.5],  
    "rf__criterion":       ["gini"], 
}

In [155]:
from sklearn.model_selection import GridSearchCV
search = GridSearchCV(
    estimator=rf_pipe,
    param_grid=param_grid,
    cv=cv,
    scoring="accuracy",
    n_jobs=-1,
    verbose=1
)

search.fit(X_train, y_train)

Fitting 10 folds for each of 432 candidates, totalling 4320 fits

GridSearchCV(cv=RepeatedStratifiedKFold(n_repeats=2, n_splits=5, random_state=42),
             estimator=Pipeline(steps=[('scaler', RobustScaler()),
                                       ('rf',
                                        RandomForestClassifier(class_weight='balanced_subsample',
                                                               random_state=42))]),
             n_jobs=-1,
             param_grid={'rf__criterion': ['gini'],
                         'rf__max_depth': [None, 8, 12, 16],
                         'rf__max_features': ['sqrt', 'log2', 0.5],
                         'rf__min_samples_leaf': [1, 2, 4],
                         'rf__min_samples_split': [2, 5, 10],
                         'rf__n_estimators': [300, 600, 900, 1200]},
             scoring='accuracy', verbose=1)

In [156]:

print("Best params:", search.best_params_)
print("Best CV accuracy:", search.best_score_)
best_rf = search.best_estimator_

Best params: {'rf__criterion': 'gini', 'rf__max_depth': None, 'rf__max_features': 0.5, 'rf__min_samples_leaf': 2, 'rf__min_samples_split': 2, 'rf__n_estimators': 1200}
Best CV accuracy: 0.6724264705882353

In [159]:
param_grid = {
    "rf__n_estimators":      [1100, 1150, 1200, 1250],        
    "rf__max_depth":         [None],      
    "rf__min_samples_split": [2, 3],
    "rf__min_samples_leaf":  [1, 2, 3],
    "rf__max_features":      ["sqrt", "log2", 0.5],  
    "rf__criterion":       ["gini"], 
}

In [160]:
from sklearn.model_selection import GridSearchCV
search = GridSearchCV(
    estimator=rf_pipe,
    param_grid=param_grid,
    cv=cv,
    scoring="accuracy",
    n_jobs=-1,
    verbose=1
)

search.fit(X_train, y_train)

Fitting 10 folds for each of 72 candidates, totalling 720 fits

GridSearchCV(cv=RepeatedStratifiedKFold(n_repeats=2, n_splits=5, random_state=42),
             estimator=Pipeline(steps=[('scaler', RobustScaler()),
                                       ('rf',
                                        RandomForestClassifier(class_weight='balanced_subsample',
                                                               random_state=42))]),
             n_jobs=-1,
             param_grid={'rf__criterion': ['gini'], 'rf__max_depth': [None],
                         'rf__max_features': ['sqrt', 'log2', 0.5],
                         'rf__min_samples_leaf': [1, 2, 3],
                         'rf__min_samples_split': [2, 3],
                         'rf__n_estimators': [1100, 1150, 1200, 1250]},
             scoring='accuracy', verbose=1)

In [161]:
print("Best params:", search.best_params_)
print("Best CV accuracy:", search.best_score_)
best_rf = search.best_estimator_

Best params: {'rf__criterion': 'gini', 'rf__max_depth': None, 'rf__max_features': 0.5, 'rf__min_samples_leaf': 2, 'rf__min_samples_split': 2, 'rf__n_estimators': 1250}
Best CV accuracy: 0.6738970588235293

In [162]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1, random_state=42, class_weight="balanced"),
    random_state=42
)
ada_pipe = Pipeline([
    ("scaler", scaler),
    ("ada", ada)
])

In [200]:

param_grid = {
    "ada__learning_rate": [0.01, 0.05, 0.1, 0.2, 0.3],
    "ada__n_estimators": [300, 500, 700, 900, 1100],
    "ada__estimator__max_depth": [1, 2, 3],
    "ada__estimator__min_samples_leaf": [1, 2, 3, 4, 5],
    "ada__estimator__class_weight": [None]
}

ada_grid = GridSearchCV(
    estimator=ada_pipe,
    param_grid=param_grid,
    scoring="accuracy",
    cv=cv,
    n_jobs=-1,
    verbose=1
)

ada_grid.fit(X_train, y_train)
print("Best params:", ada_grid.best_params_)
print("Best CV accuracy:", ada_grid.best_score_)
best_ada = ada_grid.best_estimator_

Fitting 10 folds for each of 375 candidates, totalling 3750 fits
Best params: {'ada__estimator__class_weight': None, 'ada__estimator__max_depth': 3, 'ada__estimator__min_samples_leaf': 5, 'ada__learning_rate': 0.3, 'ada__n_estimators': 1100}
Best CV accuracy: 0.5540441176470589

In [202]:

param_grid = {
    "ada__learning_rate": [0.25, 0.275, 0.3],
    "ada__n_estimators": [1050, 1100, 1200, 1250],
    "ada__estimator__max_depth": [2, 3],
    "ada__estimator__min_samples_leaf": [4, 5, 6],
    "ada__estimator__class_weight": [None]
}

ada_grid = GridSearchCV(
    estimator=ada_pipe,
    param_grid=param_grid,
    scoring="accuracy",
    cv=cv,
    n_jobs=-1,
    verbose=1
)

ada_grid.fit(X_train, y_train)
print("Best params:", ada_grid.best_params_)
print("Best CV accuracy:", ada_grid.best_score_)
best_ada = ada_grid.best_estimator_

Fitting 10 folds for each of 72 candidates, totalling 720 fits
Best params: {'ada__estimator__class_weight': None, 'ada__estimator__max_depth': 3, 'ada__estimator__min_samples_leaf': 5, 'ada__learning_rate': 0.3, 'ada__n_estimators': 1250}
Best CV accuracy: 0.55625

In [215]:
from sklearn.linear_model import LogisticRegression
logit_pipe = Pipeline([
    ("scaler", RobustScaler()),
    ("lr", LogisticRegression(
        solver="saga",                
        max_iter=100000,               
        n_jobs=-1,
        random_state=42
    ))
])

In [216]:
from sklearn.preprocessing import StandardScaler
param_grid_lr = {
    # Try both scalers (sometimes StandardScaler edges out Robust for LR)
    "scaler": [RobustScaler(), StandardScaler()],

    "lr__penalty": ["elasticnet"],

    "lr__C": np.logspace(-4, 3, 10),   # 1e-4 … 1e3

    "lr__l1_ratio": [0.0, 0.25, 0.5, 0.75],

    # Class weight (accuracy may prefer None; still test balanced)
    "lr__class_weight": [None, "balanced"],

    # Convergence tolerance (slightly tighter can help)
    "lr__tol": [1e-4, 1e-5],
}

In [217]:
lr_search = GridSearchCV(
    estimator=logit_pipe,
    param_grid=param_grid_lr,
    scoring="accuracy",
    cv=cv,
    n_jobs=-1,
    verbose=1
)

lr_search.fit(X_train, y_train)

Fitting 10 folds for each of 320 candidates, totalling 3200 fits

GridSearchCV(cv=RepeatedStratifiedKFold(n_repeats=2, n_splits=5, random_state=42),
             estimator=Pipeline(steps=[('scaler', RobustScaler()),
                                       ('lr',
                                        LogisticRegression(max_iter=100000,
                                                           n_jobs=-1,
                                                           random_state=42,
                                                           solver='saga'))]),
             n_jobs=-1,
             param_grid={'lr__C': array([1.00000000e-04, 5.99484250e-04, 3.59381366e-03, 2.15443469e-02,
       1.29154967e-01, 7.74263683e-01, 4.64158883e+00, 2.78255940e+01,
       1.66810054e+02, 1.00000000e+03]),
                         'lr__class_weight': [None, 'balanced'],
                         'lr__l1_ratio': [0.0, 0.25, 0.5, 0.75],
                         'lr__penalty': ['elasticnet'],
                         'lr__tol': [0.0001, 1e-05],
                         'scaler': [RobustScaler(), StandardScaler()]},
             scoring='accuracy', verbose=1)

In [218]:

print("LR best params:", lr_search.best_params_)
print("LR best CV accuracy:", lr_search.best_score_)

best_lr = lr_search.best_estimator_

LR best params: {'lr__C': np.float64(27.825594022071257), 'lr__class_weight': None, 'lr__l1_ratio': 0.25, 'lr__penalty': 'elasticnet', 'lr__tol': 1e-05, 'scaler': RobustScaler()}
LR best CV accuracy: 0.4448529411764707

Ensembling of the two best models

In [219]:
from sklearn.ensemble import VotingClassifier
ensemble = VotingClassifier(
    estimators=[("rf", best_rf), ("ada", best_ada)],
    voting="soft", weights=[1,1]
)

Tunning ensemble weights

In [220]:
weight_grid = {"weights": [(1,1),(2,1),(1,2),(3,1),(1,3),(4,1),(1,4)]}

In [221]:
vote_search = GridSearchCV(
    estimator=ensemble,
    param_grid=weight_grid,
    scoring="accuracy",
    cv=cv,
    n_jobs=-1,
    verbose=0
)

vote_search.fit(X_train, y_train)

GridSearchCV(cv=RepeatedStratifiedKFold(n_repeats=2, n_splits=5, random_state=42),
             estimator=VotingClassifier(estimators=[('rf',
                                                     Pipeline(steps=[('scaler',
                                                                      RobustScaler()),
                                                                     ('rf',
                                                                      RandomForestClassifier(class_weight='balanced_subsample',
                                                                                             max_features=0.5,
                                                                                             min_samples_leaf=2,
                                                                                             n_estimators=1250,
                                                                                             random_state=42))])),
                                                    ('ada',
                                                     Pipeline(steps=[('scaler',
                                                                      RobustScaler()),
                                                                     ('ada',
                                                                      AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=3,
                                                                                                                          min_samples_leaf=5,
                                                                                                                          random_state=42),
                                                                                         learning_rate=0.3,
                                                                                         n_estimators=1250,
                                                                                         random_state=42))]))],
                                        voting='soft', weights=[1, 1]),
             n_jobs=-1,
             param_grid={'weights': [(1, 1), (2, 1), (1, 2), (3, 1), (1, 3),
                                     (4, 1), (1, 4)]},
             scoring='accuracy')

In [222]:
best_voter = vote_search.best_estimator_
print("Best weights:", vote_search.best_params_["weights"])
vote_search.best_score_

Best weights: (1, 1)

np.float64(0.6746323529411764)

In [223]:
weight_grid2 = {
    "weights": [
        # --- Balanced weights ---
        (1, 1, 1),
        (2, 1, 1),
        (1, 2, 1),
        (1, 1, 2),
        # --- RF-dominant ---
        (3, 1, 1),
        (4, 1, 1),
        # --- Ada-dominant ---
        (1, 3, 1),
        (1, 4, 1),
        # --- LR-dominant ---
        (1, 1, 3),
        (1, 1, 4),
        # --- Combined bias towards two models ---
        (2, 2, 1),
        (2, 1, 2),
        (1, 2, 2),
        # --- Edge-case extremes ---
        (5, 1, 1),
        (1, 5, 1),
        (1, 1, 5)
    ]
}

In [224]:
from sklearn.ensemble import VotingClassifier
ensemble2 = VotingClassifier(
    estimators=[("rf", best_rf), ("ada", best_ada), ("lr", best_lr)],
    voting="soft", weights=[1,1]
)

In [287]:
vote_search2 = GridSearchCV(
    estimator=ensemble2,
    param_grid=weight_grid2,
    scoring="accuracy",
    cv=cv,
    n_jobs=-1,
    verbose=0
)

vote_search2.fit(X_train, y_train)

GridSearchCV(cv=RepeatedStratifiedKFold(n_repeats=2, n_splits=5, random_state=42),
             estimator=VotingClassifier(estimators=[('rf',
                                                     Pipeline(steps=[('scaler',
                                                                      RobustScaler()),
                                                                     ('rf',
                                                                      RandomForestClassifier(class_weight='balanced_subsample',
                                                                                             max_features=0.5,
                                                                                             min_samples_leaf=2,
                                                                                             n_estimators=1250,
                                                                                             random_state=42))])),
                                                    ('ada',
                                                     Pipeline(steps=[('scaler',
                                                                      RobustScaler...
                                                                      LogisticRegression(C=np.float64(27.825594022071257),
                                                                                         l1_ratio=0.25,
                                                                                         max_iter=100000,
                                                                                         n_jobs=-1,
                                                                                         penalty='elasticnet',
                                                                                         random_state=42,
                                                                                         solver='saga',
                                                                                         tol=1e-05))]))],
                                        voting='soft', weights=[1, 1]),
             n_jobs=-1,
             param_grid={'weights': [(1, 1, 1), (2, 1, 1), (1, 2, 1), (1, 1, 2),
                                     (3, 1, 1), (4, 1, 1), (1, 3, 1), (1, 4, 1),
                                     (1, 1, 3), (1, 1, 4), (2, 2, 1), (2, 1, 2),
                                     (1, 2, 2), (5, 1, 1), (1, 5, 1),
                                     (1, 1, 5)]},
             scoring='accuracy')

In [289]:
best_voter2 = vote_search2.best_estimator_
print("Best weights:", vote_search2.best_params_["weights"])
vote_search2.best_score_

Best weights: (5, 1, 1)

np.float64(0.6511029411764706)

In [292]:
from sklearn.metrics import accuracy_score
y_pred_test_rf = best_rf.predict(X_test)
y_pred_test_voter = best_voter.predict(X_test)
y_pred_test_ada = best_ada.predict(X_test)
y_pred_test_lr = best_lr.predict(X_test)
y_pred_test_voter2 = best_voter2.predict(X_test)

acc_rf = accuracy_score(y_test, y_pred_test_rf)
print(f"RF Test Accuracy: {acc_rf:.4f}\n")

acc_voter = accuracy_score(y_test, y_pred_test_voter)
print(f"Voter Test Accuracy: {acc_voter:.4f}\n")

acc_ada = accuracy_score(y_test, y_pred_test_ada)
print(f"ADA Test Accuracy: {acc_ada:.4f}\n")

acc_lr = accuracy_score(y_test, y_pred_test_lr)
print(f"LR Test Accuracy: {acc_lr:.4f}\n")

acc_voter2 = accuracy_score(y_test, y_pred_test_voter2)
print(f"Voter2 Test Accuracy: {acc_voter2:.4f}\n")

RF Test Accuracy: 0.7294

Voter Test Accuracy: 0.7265

ADA Test Accuracy: 0.5735

LR Test Accuracy: 0.4765

Voter2 Test Accuracy: 0.7324

**Binary**

In [274]:
# BInary Classifier Data Splits
X_b = df.drop(["InvGrd", "Rating", "Rating_Group", "Total Debt", "Total Debt/MV", "Net Debt", "Net Debt/MV", "Net Income Before Extras"], axis=1)
y_b = df["InvGrd"]

X_b_train, X_b_test, y_b_train, y_b_test = train_test_split(X_b, y_b, test_size=0.2, stratify=y, random_state=42)

In [275]:
tree_pipe = Pipeline([
    ("scale", RobustScaler()),
    ("tree", DecisionTreeClassifier(random_state=42))
])

logreg_pipe = Pipeline([
    ("scale", RobustScaler()),
    ("logreg", LogisticRegression(solver="saga",                
        max_iter=100000,               
        n_jobs=-1,
        random_state=42))
])

In [276]:
tree_param_grid = {
    "tree__max_depth": [1, 3, 5, 8, 10, 14, 20],
    "tree__min_samples_leaf": [1, 5, 10],
    "tree__min_samples_split": [2, 10, 20]
}

In [277]:


tree_grid = GridSearchCV(
    estimator = tree_pipe,
    param_grid = tree_param_grid,
    scoring="accuracy",
    cv = cv,
    n_jobs = -1,
    verbose=1
)

In [278]:
tree_grid.fit(X_b_train, y_b_train)
print("Best DT params:", tree_grid.best_params_)
print("Best DT CV Accuracy:", tree_grid.best_score_)
best_tree = tree_grid.best_estimator_

Fitting 10 folds for each of 63 candidates, totalling 630 fits
Best DT params: {'tree__max_depth': 14, 'tree__min_samples_leaf': 1, 'tree__min_samples_split': 2}
Best DT CV Accuracy: 0.7860294117647058

In [279]:
logreg_param_grid = [
    {   
        "logreg__penalty": ["l1"],
        "logreg__C": np.logspace(-4, 3, 10),
    },
    {
        "logreg__penalty": ["l2"],
        "logreg__C": np.logspace(-4, 3, 10),
    },
    {
        "logreg__penalty": ["elasticnet"],
        "logreg__C": np.logspace(-4, 3, 10),
        "logreg__l1_ratio": [0.25, 0.5, 0.75],
    },
]

In [280]:
logreg_grid = GridSearchCV(
    estimator = logreg_pipe,
    param_grid = logreg_param_grid,
    scoring = "accuracy",
    cv = cv,
    n_jobs = -1,
    verbose = 1
)

In [281]:
logreg_grid.fit(X_b_train, y_b_train)
print("Best LR params:", logreg_grid.best_params_)
print("Best LR CV Accuracy:", logreg_grid.best_score_)
best_logreg = logreg_grid.best_estimator_

Fitting 10 folds for each of 50 candidates, totalling 500 fits
Best LR params: {'logreg__C': np.float64(0.0001), 'logreg__penalty': 'l1'}
Best LR CV Accuracy: 0.7573529411764707

In [282]:
ensemble_binary = VotingClassifier(
    estimators=[("dTree", best_tree), ("log_reg", best_logreg)],
    voting="soft", weights=[1,1]
)

In [283]:
weight_grid = {"weights": [(1,1),(2,1),(1,2),(3,1),(1,3),(4,1),(1,4)]}

In [284]:
vote_search_binary = GridSearchCV(
    estimator=ensemble_binary,
    param_grid=weight_grid,
    scoring="accuracy",
    cv=cv,
    n_jobs=-1,
    verbose=0
)

vote_search_binary.fit(X_b_train, y_b_train)

GridSearchCV(cv=RepeatedStratifiedKFold(n_repeats=2, n_splits=5, random_state=42),
             estimator=VotingClassifier(estimators=[('dTree',
                                                     Pipeline(steps=[('scale',
                                                                      RobustScaler()),
                                                                     ('tree',
                                                                      DecisionTreeClassifier(max_depth=14,
                                                                                             random_state=42))])),
                                                    ('log_reg',
                                                     Pipeline(steps=[('scale',
                                                                      RobustScaler()),
                                                                     ('logreg',
                                                                      LogisticRegression(C=np.float64(0.0001),
                                                                                         max_iter=100000,
                                                                                         n_jobs=-1,
                                                                                         penalty='l1',
                                                                                         random_state=42,
                                                                                         solver='saga'))]))],
                                        voting='soft', weights=[1, 1]),
             n_jobs=-1,
             param_grid={'weights': [(1, 1), (2, 1), (1, 2), (3, 1), (1, 3),
                                     (4, 1), (1, 4)]},
             scoring='accuracy')

In [285]:
best_voter_binary = vote_search_binary.best_estimator_
print("Best weights:", vote_search_binary.best_params_["weights"])
vote_search_binary.best_score_

Best weights: (1, 1)

np.float64(0.7860294117647058)

In [286]:
y_pred_test_tree = best_tree.predict(X_b_test)
y_pred_test_logreg = best_logreg.predict(X_b_test)
y_pred_test_voter_binary = best_voter_binary.predict(X_b_test)

acc_tree = accuracy_score(y_b_test, y_pred_test_tree)
print(f"dTree Test Accuracy: {acc_tree:.4f}\n")

acc_logreg = accuracy_score(y_b_test, y_pred_test_logreg)
print(f"LogReg Test Accuracy: {acc_rf:.4f}\n")

acc_voter_bin = accuracy_score(y_b_test, y_pred_test_voter_binary)
print(f"Binary Voter Test Accuracy: {acc_voter_bin:.4f}\n")

dTree Test Accuracy: 0.8176

LogReg Test Accuracy: 0.7294

Binary Voter Test Accuracy: 0.8176